---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@0ef7f561e899508b7425574ce3d9e9f57ced6154 # main
    name: Module Validation
    with:
      working-directory: .
